### PR TITLE
Finish Recipe test

### PR DESCRIPTION
**Pull request by aspitz1**
#### 'Recipe' should hold array of ingredients needed, 
`Recipe` should determine the names of ingredients needed,
`Recipe` should get cost of ingredients,
`Recipe` returns its directions/instructions

********************************************************************

```
/** All ideas, names and code below can be altered in any way **/ 
// Recipe starts with ingredientsNeeded key that is unassigned to a 
// value

// ingredient data .map() over to create new array that is  
// instances of the Ingredient class. This method is called first
// first thing in the method that pulls out just the ingredients 
// needed

// Inside of the ingredientsNeeded method:
// First assign a variable too the method described above method named ingredientData.
// Recipe has method that .map() over ingredients in recipe array to create an  
// array of ID's then .map() over ID's to to .find() and return matching 
// ingredients from the ingredients data array. 
// Return will be stored in recipie.ingredientsNeeded
// below is some code to help explain the thought process above:

// const igredientIds = this.ingredients.map(ingredient => {ingredient.id})
// const ingredientNames = this.ingredientsIds.map(ingredientId => {
//  return ingredientData.find(ingredientObj => {
//    if (ingredientObj.id === ingredientId) {
//         return ingredinetObj
//    } 
//})
//})
//inside Recipe
// buildIngredientsNeeded(ingredients) {
//    const ingredients = this.getAllIngredients(ingedints)

//    const igredientIds = this.ingredients.map(igredient => {ingredient.id})
//    const this.ingredientsNeeded = this.ingredientsIds.map(ingredientId => {
//    return ingredientData.find(ingredientObj => {
//    if (ingredientObj.id === ingredientId) {
//         return ingredinetObj
//    } 
//}
```

### CODE REVIEW

**Review by AnaBennett11 — APPROVED** [review]
Everything looks great. Good job completing the rest of those tests on the Recipe-test.js.

**Comment by aspitz1** [comment]
thank you for the review @AnaBennett11 :) I had a thought after our lesson today I wanted to share.

We may want to hold off on merging this. The raw data in the ingredients and recipes data sheets may be un-parsed json. If that’s the case we may need to be considering how that will go into our class methods. 

Essentially I am assuming the data sheets we are given may closely resemble the data we get from fetch() using the provided recipe API. If that’s the case we may want to be passing them into our tests as is (not removing the quotes?). Then parsing them ether in the test or in the method. 

Do ya’ll have any thought on this?

**Comment by aspitz1** [comment]
> 

Also, this may not be something we do in our classes, but rather before we pass in the data as an argument? Like in the `then()` method.

**Comment by aspitz1** [comment]
I did a bit more experimenting, and if I `console.log()` a single object from the ingredientsData.js, it does log a object, NOT a `json` string. That is w/o removing the quotations around the keys. I am still curious about those quotes, and think we should look into it. I don't think it should keep us from moving forward with what we have wrote so far though.

LMK what ya'll think. Thank you for reading my comments!

**Pull request merged**
